# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4d86bca0850ced772912eda46f5d003e08831fcb08721dc21a38695087fda270f51600ea74c0261a146143c6b74201fd8b7c3d3cfcad63d21cfb599a4267cabe

test:
  secret_key_base: d57129a8282fac43c487ef989142532d8baa20f1c826f5af33fba451f8f83591f9b65ad62c213c3fef27fa9a7a51da5e73e5f89c2c0579e8c96e7b678a124a2f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
